// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

// type Iurl = {
//   usr: string;
//   pswrd: string;
//   dbname: string;
//   host: string;
//   port: string;
// };

// function urlBuilder({ usr, pswrd, dbname, host, port }: Iurl) {
//   return `postgres://${usr}:${pswrd}@${host}:${port}/${dbname}`;
// }

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
