
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Transaction_T = {
  income: 'income',
  expense: 'expense'
} as const

export type Transaction_T = (typeof Transaction_T)[keyof typeof Transaction_T]
